archives:
  - format: tar.gz
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux
builds:
  - main: ./
    goos:
      #- windows
      - darwin
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
